/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Disclosure {
  export type RecordStruct = {
    cid: string;
    aiUsed: boolean;
    timestamp: BigNumberish;
    creator: AddressLike;
  };

  export type RecordStructOutput = [
    cid: string,
    aiUsed: boolean,
    timestamp: bigint,
    creator: string
  ] & { cid: string; aiUsed: boolean; timestamp: bigint; creator: string };
}

export interface DisclosureInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addRecord"
      | "getAllRecords"
      | "getLatestRecord"
      | "getTotalRecords"
      | "hasSubmitted"
      | "records"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RecordAdded"): EventFragment;

  encodeFunctionData(
    functionFragment: "addRecord",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllRecords",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestRecord",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalRecords",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasSubmitted",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "records",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addRecord", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "records", data: BytesLike): Result;
}

export namespace RecordAddedEvent {
  export type InputTuple = [
    contentHash: string,
    aiUsed: boolean,
    creator: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    contentHash: string,
    aiUsed: boolean,
    creator: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    contentHash: string;
    aiUsed: boolean;
    creator: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Disclosure extends BaseContract {
  connect(runner?: ContractRunner | null): Disclosure;
  waitForDeployment(): Promise<this>;

  interface: DisclosureInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addRecord: TypedContractMethod<
    [_hash: string, _aiUsed: boolean],
    [void],
    "nonpayable"
  >;

  getAllRecords: TypedContractMethod<
    [_hash: string],
    [Disclosure.RecordStructOutput[]],
    "view"
  >;

  getLatestRecord: TypedContractMethod<
    [_hash: string],
    [Disclosure.RecordStructOutput],
    "view"
  >;

  getTotalRecords: TypedContractMethod<[], [bigint], "view">;

  hasSubmitted: TypedContractMethod<
    [arg0: string, arg1: AddressLike],
    [boolean],
    "view"
  >;

  records: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, boolean, bigint, string] & {
        cid: string;
        aiUsed: boolean;
        timestamp: bigint;
        creator: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addRecord"
  ): TypedContractMethod<
    [_hash: string, _aiUsed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllRecords"
  ): TypedContractMethod<
    [_hash: string],
    [Disclosure.RecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLatestRecord"
  ): TypedContractMethod<
    [_hash: string],
    [Disclosure.RecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalRecords"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasSubmitted"
  ): TypedContractMethod<[arg0: string, arg1: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "records"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, boolean, bigint, string] & {
        cid: string;
        aiUsed: boolean;
        timestamp: bigint;
        creator: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "RecordAdded"
  ): TypedContractEvent<
    RecordAddedEvent.InputTuple,
    RecordAddedEvent.OutputTuple,
    RecordAddedEvent.OutputObject
  >;

  filters: {
    "RecordAdded(string,bool,address,uint256)": TypedContractEvent<
      RecordAddedEvent.InputTuple,
      RecordAddedEvent.OutputTuple,
      RecordAddedEvent.OutputObject
    >;
    RecordAdded: TypedContractEvent<
      RecordAddedEvent.InputTuple,
      RecordAddedEvent.OutputTuple,
      RecordAddedEvent.OutputObject
    >;
  };
}
